DROP TABLE IF EXISTS `migrantworkers_renewal`;
CREATE TABLE `migrantworkers_renewal` (
  `migrantworkers_renewal_id` int(11) NOT NULL AUTO_INCREMENT,
  `mw_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `registration_number` varchar(11) NOT NULL,
  `name_of_establishment` varchar(100) NOT NULL,
  `location_of_establishment` text NOT NULL,
  `postal_address_of_establishment` text NOT NULL,
  `principal_employer_name` varchar(100) NOT NULL,
  `principal_employer_address` text NOT NULL,
  `directors_or_partners_name` varchar(100) NOT NULL,
  `directors_or_partners_address` text NOT NULL,
  `manager_or_persons_name` varchar(100) NOT NULL,
  `manager_or_persons_address` text NOT NULL,
  `nature_of_work_of_establishment` varchar(200) NOT NULL,
  `contractor_details` text NOT NULL,
  `name_of_bank` text NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `challan_no` varchar(100) NOT NULL,
  `challan_date` date NOT NULL,
  `valid_upto` date NOT NULL,
  `last_valid_upto` date NOT NULL,
  `signature` varchar(50) NOT NULL,
  `remarks` text NOT NULL,
  `payment_type` tinyint(1) NOT NULL,
  `user_payment_type` tinyint(1) NOT NULL,
  `submitted_datetime` datetime NOT NULL,
  `processing_days` int(11) NOT NULL,
  `query_status` tinyint(1) NOT NULL,
  `challan` varchar(100) NOT NULL,
  `challan_updated_date` datetime NOT NULL,
  `fees_paid_challan` varchar(100) NOT NULL,
  `fees_paid_challan_updated_date` datetime NOT NULL,
  `status` tinyint(1) NOT NULL,
  `status_datetime` datetime NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_time` datetime NOT NULL,
  `updated_by` int(11) NOT NULL,
  `updated_time` datetime NOT NULL,
  `is_delete` tinyint(1) NOT NULL,
  PRIMARY KEY (`migrantworkers_renewal_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Adminer 4.6.2 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `shop_renewal`;
CREATE TABLE `shop_renewal` (
  `shop_renewal_id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `name_of_shop` varchar(100) NOT NULL,
  `total_employees` varchar(100) NOT NULL,
  `employer_name` varchar(100) NOT NULL,
  `employer_mobile_no` varchar(10) NOT NULL,
  `employer_residential_address` text NOT NULL,
  `manager_name` varchar(100) NOT NULL,
  `manager_residential_address` text NOT NULL,
  `category` varchar(100) NOT NULL,
  `signature` varchar(100) NOT NULL,
  `submitted_datetime` datetime NOT NULL,
  `status` tinyint(1) NOT NULL,
  `status_datetime` datetime NOT NULL,
  `processing_days` int(11) NOT NULL,
  `challan` varchar(100) NOT NULL,
  `challan_updated_date` datetime NOT NULL,
  `challan_number` varchar(100) NOT NULL,
  `fees_paid_challan` varchar(100) NOT NULL,
  `fees_paid_challan_updated_date` datetime NOT NULL,
  `registration_number` varchar(100) NOT NULL,
  `valid_upto` date NOT NULL,
  `last_valid_upto` date NOT NULL,
  `remarks` varchar(200) NOT NULL,
  `payment_type` tinyint(1) NOT NULL,
  `user_payment_type` tinyint(1) NOT NULL,
  `query_status` tinyint(1) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_time` datetime NOT NULL,
  `updated_by` int(11) NOT NULL,
  `updated_time` datetime NOT NULL,
  `is_delete` tinyint(1) NOT NULL,
  PRIMARY KEY (`shop_renewal_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 2020-12-24 06:12:23

CREATE TABLE `na` (
  `na_id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` int NOT NULL,
  `name_of_applicant` varchar(100) NOT NULL,
  `postel_address` varchar(100) NOT NULL,
  `purpose` varchar(100) NOT NULL,
  `occupation` varchar(100) NOT NULL,
  `district` varchar(100) NOT NULL,
  `village` varchar(100) NOT NULL,
  `survey_no` varchar(100) NOT NULL,
  `area_of_site_used` varchar(100) NOT NULL,
  `occupant_class` varchar(100) NOT NULL,
  `present_use_land` varchar(100) NOT NULL,
  `situated_land` varchar(100) NOT NULL,
  `electrical_distance_land` varchar(5) NOT NULL,
  `acquisition_under_land` varchar(5) NOT NULL,
  `accessible_land` varchar(5) NOT NULL,
  `site_access_land` varchar(5) NOT NULL,
  `rejected_land` varchar(5) NOT NULL,
  `form_land_document` varchar(100) NOT NULL,
  `site_plan_document` varchar(100) NOT NULL,
  `signature` varchar(100) NOT NULL,
  `submitted_datetime` datetime NOT NULL,
  `status` tinyint(1) NOT NULL,
  `status_datetime` datetime NOT NULL,
  `processing_days` int NOT NULL,
  `challan` varchar(100) NOT NULL,
  `challan_updated_date` varchar(100) NOT NULL,
  `fees_paid_challan` varchar(100) NOT NULL,
  `fees_paid_challan_updated_date` datetime NOT NULL,
  `registration_number` varchar(100) NOT NULL,
  `valid_upto` date NOT NULL,
  `remarks` varchar(200) NOT NULL,
  `payment_type` tinyint(1) NOT NULL,
  `user_payment_type` tinyint(1) NOT NULL,
  `query_status` tinyint(1) NOT NULL,
  `created_by` int NOT NULL,
  `created_time` datetime NOT NULL,
  `updated_by` int NOT NULL,
  `updated_time` datetime NOT NULL,
  `is_delete` tinyint(1) NOT NULL
);